text = ('Hello world')
name = ('Valeriia')
last_name = ('Barabash')
age = 16
print(text)
print(name, last_name)
print(age)
print(type(text))
print(type(name))
print(type(last_name))
print(type(age))